import { createHash } from 'node:crypto';
import type { RepoContext, RenderedFile, Target } from './types.js';

const yaml = (context: RepoContext) => `repository:\n  name: ${context.repository.name}\n  primary_language: ${context.repository.primaryLanguage ?? 'null'}\n  languages: [${context.repository.languages.join(', ')}]\nstack:\n  runtime: ${context.stack.runtime ?? 'null'}\n  frameworks: [${context.stack.frameworks.join(', ')}]\nstructure:\n  directories: [${context.structure.directories.join(', ')}]\n  entry_points: [${context.structure.entryPoints.join(', ')}]\ncommands:\n  build: ${context.commands.build ?? 'null'}\n  test: ${context.commands.test ?? 'null'}\n  dev: ${context.commands.dev ?? 'null'}\nconstraints:\n${context.constraints.map((x) => `  - ${x}`).join('\n')}\n`;

const json = (context: RepoContext) => JSON.stringify({
  ...context,
  systemPrompt: `You are an evidence-driven assistant for ${context.repository.name}. Follow the repository constraints and do not invent missing facts.`
}, null, 2) + '\n';

const marker = (context: RepoContext) => createHash('sha256').update(JSON.stringify(context)).digest('hex').slice(0, 12);

export function render(context: RepoContext, target: Exclude<Target, 'all'>): RenderedFile[] {
  const hash = marker(context);
  const header = `<!-- Generated by ai-meta-factory; context ${hash}. Do not edit manually. -->\n`;
  const summary = `# ${context.repository.name} — Project Context\n\n- Languages: ${context.repository.languages.join(', ') || 'unknown'}\n- Runtime: ${context.stack.runtime ?? 'unknown'}\n- Frameworks: ${context.stack.frameworks.join(', ') || 'none detected'}\n- Entry points: ${context.structure.entryPoints.join(', ') || 'none detected'}\n- Directories: ${context.structure.directories.join(', ') || 'none detected'}\n- Constraints: ${context.constraints.join(' ')}\n`;

  switch (target) {
    case 'cursor':
      return [
        {
          path: '.cursor/rules/000-project-context.mdc',
          content: `---\nalwaysApply: true\nname: "000-project-context"\ndescription: "Generated repository reference"\n---\n${header}${summary}`
        },
        { path: 'meta/factory/repo-context.yaml', content: yaml(context) }
      ];
    case 'github-copilot':
      return [
        {
          path: '.github/copilot-instructions.md',
          content: `${header}${summary}\nUse the existing project structure and commands. Do not infer undocumented architecture.`
        },
        { path: 'meta/factory/repo-context.yaml', content: yaml(context) }
      ];
    case 'claude':
      return [
        {
          path: 'CLAUDE.md',
          content: `${header}${summary}\n## Reasoning rules\nUse only observable repository evidence. Preserve architectural boundaries and ask before changing generated context.\n`
        },
        { path: 'meta/factory/repo-context.yaml', content: yaml(context) }
      ];
    case 'gemini':
      return [
        { path: 'gemini-context.json', content: json(context) },
        { path: 'meta/factory/repo-context.yaml', content: yaml(context) }
      ];
    case 'generic':
      return [
        { path: '.ai-context/repo-context.json', content: json(context) },
        { path: '.ai-context/README.md', content: `${header}This directory contains generated, tool-neutral repository context. Regenerate after structural changes.\n` }
      ];
  }
}

export function targets(value: Target): Exclude<Target, 'all'>[] {
  return value === 'all' ? ['cursor', 'github-copilot', 'claude', 'gemini', 'generic'] : [value];
}
