import { createHash } from 'node:crypto';
import type { RepoContext, RenderedFile, StageOutput, PromptStage, Target } from './types.js';

const marker = (context: RepoContext) => createHash('sha256').update(JSON.stringify(context)).digest('hex').slice(0, 12);

const header = (context: RepoContext) => `<!-- Generated by ai-meta-factory; context ${marker(context)}. Do not edit manually. -->
`;

const summary = (context: RepoContext) => `# ${context.repository.name} — Project Context

- Languages: ${context.repository.languages.join(', ') || 'unknown'}
- Runtime: ${context.stack.runtime ?? 'unknown'}
- Frameworks: ${context.stack.frameworks.join(', ') || 'none'}
- Package Manager: ${context.stack.packageManager ?? 'unknown'}

## Entry Points
${context.structure.entryPoints.map((ep) => `- ${ep}`).join('\n') || 'None detected'}

## Key Directories
${context.structure.directories.map((dir) => `- ${dir}/`).join('\n') || 'None'}

## Build Commands
- Build: \`${context.commands.build ?? 'N/A'}\`
- Test: \`${context.commands.test ?? 'N/A'}\`
- Dev: \`${context.commands.dev ?? 'N/A'}\`

## Constraints
${context.constraints.map((c) => `- ${c}`).join('\n')}
`;

// ============================================================================
// SCANNER STAGE - Common to all targets
// ============================================================================
export function stageScanner(context: RepoContext): RenderedFile[] {
  return [
    {
      path: 'meta/factory/repo-context.yaml',
      content: `repository:
  name: ${context.repository.name}
  description: ${context.repository.description ?? 'null'}
  primary_language: ${context.repository.primaryLanguage ?? 'null'}
  languages: [${context.repository.languages.join(', ')}]

stack:
  frameworks: [${context.stack.frameworks.join(', ')}]
  package_manager: ${context.stack.packageManager ?? 'null'}
  runtime: ${context.stack.runtime ?? 'null'}

structure:
  directories: [${context.structure.directories.join(', ')}]
  entry_points: [${context.structure.entryPoints.join(', ')}]

conventions:
  files: ${context.conventions.files ?? 'null'}
  tests: ${context.conventions.tests ?? 'null'}

commands:
  build: ${context.commands.build ?? 'null'}
  test: ${context.commands.test ?? 'null'}
  dev: ${context.commands.dev ?? 'null'}

constraints:
${context.constraints.map((c) => `  - ${c}`).join('\n')}

generated_at: ${context.generatedAt}
`
    }
  ];
}

// ============================================================================
// CONTEXT GENERATOR STAGE - Target-specific implementations
// ============================================================================
function contextGeneratorCursor(context: RepoContext): RenderedFile[] {
  return [
    {
      path: '.cursor/rules/000-project-context.mdc',
      content: `---
alwaysApply: true
name: "000-project-context"
description: "Generated repository reference"
---
${header(context)}${summary(context)}`
    }
  ];
}

function contextGeneratorGithubCopilot(context: RepoContext): RenderedFile[] {
  return [
    {
      path: '.github/copilot-instructions.md',
      content: `${header(context)}${summary(context)}`
    }
  ];
}

function contextGeneratorClaude(context: RepoContext): RenderedFile[] {
  return [
    {
      path: 'CLAUDE.md',
      content: `${header(context)}${summary(context)}`
    }
  ];
}

function contextGeneratorGemini(context: RepoContext): RenderedFile[] {
  return [
    {
      path: 'gemini-context.json',
      content: JSON.stringify({
        repository: context.repository,
        stack: context.stack,
        structure: context.structure,
        conventions: context.conventions,
        commands: context.commands,
        constraints: context.constraints
      }, null, 2) + '\n'
    }
  ];
}

function contextGeneratorGeneric(context: RepoContext): RenderedFile[] {
  return [
    {
      path: '.ai-context/repo-context.json',
      content: JSON.stringify({
        ...context,
        systemPrompt: `You are an evidence-driven assistant for ${context.repository.name}. Follow the repository constraints and do not invent missing facts.`
      }, null, 2) + '\n'
    },
    {
      path: '.ai-context/context-generator.md',
      content: `${header(context)}# Context Generator Output

Generated context lookup table for AI agents.

${summary(context)}`
    }
  ];
}

export function stageContextGenerator(context: RepoContext, target: Exclude<Target, 'all'>): RenderedFile[] {
  switch (target) {
    case 'cursor':
      return contextGeneratorCursor(context);
    case 'github-copilot':
      return contextGeneratorGithubCopilot(context);
    case 'claude':
      return contextGeneratorClaude(context);
    case 'gemini':
      return contextGeneratorGemini(context);
    case 'generic':
      return contextGeneratorGeneric(context);
  }
}

// ============================================================================
// ARCHITECTURE STAGE - Target-specific implementations
// ============================================================================
function architectureCursor(context: RepoContext): RenderedFile[] {
  return [
    {
      path: '.cursor/rules/200-architecture.mdc',
      content: `---
alwaysApply: true
name: "200-architecture"
description: "Architecture and module boundaries"
---
${header(context)}# Architecture Overview

## Module Structure
${context.structure.directories.map((dir) => `- **${dir}/** — Module boundary`).join('\n') || 'No modules detected'}

## Entry Points
${context.structure.entryPoints.map((ep) => `- ${ep}`).join('\n')}

## Dependency Rules
1. Preserve existing module boundaries
2. Do not create circular dependencies
3. Follow the directory structure for imports
4. Use absolute imports when possible

## Constraints
${context.constraints.map((c) => `- ${c}`).join('\n')}
`
    }
  ];
}

function architectureGithubCopilot(context: RepoContext): RenderedFile[] {
  return [
    {
      path: '.github/architecture.md',
      content: `${header(context)}# Architecture Overview

## Module Structure
${context.structure.directories.map((dir) => `- **${dir}/** — Module boundary`).join('\n') || 'No modules detected'}

## Entry Points
${context.structure.entryPoints.map((ep) => `- ${ep}`).join('\n')}

## Dependency Rules
1. Preserve existing module boundaries
2. Do not create circular dependencies
3. Follow the directory structure for imports
`
    }
  ];
}

function architectureClaude(context: RepoContext): RenderedFile[] {
  return [
    {
      path: 'ARCHITECTURE.md',
      content: `${header(context)}# Architecture Overview

## Module Structure
${context.structure.directories.map((dir) => `- **${dir}/** — Module boundary`).join('\n') || 'No modules detected'}

## Entry Points
${context.structure.entryPoints.map((ep) => `- ${ep}`).join('\n')}

## Dependency Rules
1. Preserve existing module boundaries
2. Do not create circular dependencies
3. Follow the directory structure for imports
`
    }
  ];
}

function architectureGemini(context: RepoContext): RenderedFile[] {
  return [
    {
      path: 'gemini-architecture.json',
      content: JSON.stringify({
        modules: context.structure.directories,
        entryPoints: context.structure.entryPoints,
        dependencies: 'See repository structure',
        constraints: context.constraints
      }, null, 2) + '\n'
    }
  ];
}

function architectureGeneric(context: RepoContext): RenderedFile[] {
  return [
    {
      path: '.ai-context/architecture.md',
      content: `${header(context)}# Architecture Overview

## Module Structure
${context.structure.directories.map((dir) => `- **${dir}/** — Module boundary`).join('\n') || 'No modules detected'}

## Entry Points
${context.structure.entryPoints.map((ep) => `- ${ep}`).join('\n')}

## Dependency Rules
1. Preserve existing module boundaries
2. Do not create circular dependencies
3. Follow the directory structure for imports
`
    }
  ];
}

export function stageArchitecture(context: RepoContext, target: Exclude<Target, 'all'>): RenderedFile[] {
  switch (target) {
    case 'cursor':
      return architectureCursor(context);
    case 'github-copilot':
      return architectureGithubCopilot(context);
    case 'claude':
      return architectureClaude(context);
    case 'gemini':
      return architectureGemini(context);
    case 'generic':
      return architectureGeneric(context);
  }
}

// ============================================================================
// STANDARDS STAGE - Target-specific implementations
// ============================================================================
function standardsCursor(context: RepoContext): RenderedFile[] {
  const primaryLang = context.repository.primaryLanguage || 'TypeScript';
  return [
    {
      path: '.cursor/rules/100-typescript-standards.mdc',
      content: `---
alwaysApply: true
name: "100-typescript-standards"
description: "Coding standards for ${primaryLang}"
---
${header(context)}# ${primaryLang} Coding Standards

## File Naming
- Use kebab-case for files: \`auth-service.ts\`
- Use PascalCase for classes: \`class AuthService {}\`
- Use camelCase for functions and variables

## Code Style
- Use strict mode: \`"use strict;"\` or \`strict: true\` in tsconfig
- Prefer \`const\` over \`let\` and \`var\`
- Use type annotations for function parameters and returns
- Keep functions small and focused (max 50 lines)

## Imports
- Organize imports: relative -> monorepo -> external -> types
- Use absolute paths from configured aliases
- Avoid circular dependencies

## Testing
- Write tests for all public APIs
- Use descriptive test names
- Keep test files adjacent to source files
- Aim for >80% code coverage

## Documentation
- Add JSDoc comments to public functions
- Document complex logic with inline comments
- Keep README files updated
`
    }
  ];
}

function standardsGithubCopilot(context: RepoContext): RenderedFile[] {
  const primaryLang = context.repository.primaryLanguage || 'TypeScript';
  return [
    {
      path: '.github/standards.md',
      content: `# ${primaryLang} Coding Standards

## File Naming
- Use kebab-case for files: \`auth-service.ts\`
- Use PascalCase for classes: \`class AuthService {}\`
- Use camelCase for functions and variables

## Code Style
- Use strict mode
- Prefer \`const\` over \`let\` and \`var\`
- Use type annotations for function parameters
- Keep functions small and focused
`
    }
  ];
}

function standardsClaude(context: RepoContext): RenderedFile[] {
  const primaryLang = context.repository.primaryLanguage || 'TypeScript';
  return [
    {
      path: 'STANDARDS.md',
      content: `# ${primaryLang} Coding Standards

## File Naming
- Use kebab-case for files: \`auth-service.ts\`
- Use PascalCase for classes: \`class AuthService {}\`
- Use camelCase for functions and variables

## Code Style
- Use strict mode
- Prefer \`const\` over \`let\` and \`var\`
- Use type annotations for function parameters
- Keep functions small and focused
`
    }
  ];
}

function standardsGemini(context: RepoContext): RenderedFile[] {
  const primaryLang = context.repository.primaryLanguage || 'TypeScript';
  return [
    {
      path: 'gemini-standards.json',
      content: JSON.stringify({
        language: primaryLang,
        naming: { files: 'kebab-case', classes: 'PascalCase', functions: 'camelCase' },
        codeStyle: ['use strict mode', 'prefer const', 'type annotations', 'max 50 lines per function'],
        testing: 'Write tests for all public APIs'
      }, null, 2) + '\n'
    }
  ];
}

function standardsGeneric(context: RepoContext): RenderedFile[] {
  const primaryLang = context.repository.primaryLanguage || 'TypeScript';
  return [
    {
      path: '.ai-context/standards.md',
      content: `${header(context)}# ${primaryLang} Coding Standards

## File Naming
- Use kebab-case for files: \`auth-service.ts\`
- Use PascalCase for classes: \`class AuthService {}\`
- Use camelCase for functions and variables

## Code Style
- Use strict mode
- Prefer \`const\` over \`let\` and \`var\`
- Use type annotations for function parameters
- Keep functions small and focused
`
    }
  ];
}

export function stageStandards(context: RepoContext, target: Exclude<Target, 'all'>): RenderedFile[] {
  switch (target) {
    case 'cursor':
      return standardsCursor(context);
    case 'github-copilot':
      return standardsGithubCopilot(context);
    case 'claude':
      return standardsClaude(context);
    case 'gemini':
      return standardsGemini(context);
    case 'generic':
      return standardsGeneric(context);
  }
}

// ============================================================================
// TESTS STAGE - Target-specific implementations
// ============================================================================
function testsCursor(context: RepoContext): RenderedFile[] {
  return [
    {
      path: '.cursor/rules/300-test-conventions.mdc',
      content: `---
alwaysApply: true
name: "300-test-conventions"
description: "Testing patterns and requirements"
---
${header(context)}# Test Conventions

## Test Structure
- Test files: \`*.test.ts\` or \`*.spec.ts\`
- Location: adjacent to source or in \`__tests__/\` directory
- Group related tests with \`describe()\` blocks

## Test Patterns
- **Unit Tests:** Test individual functions and classes
- **Integration Tests:** Test module interactions
- **E2E Tests:** Test complete workflows

## Running Tests
${context.commands.test ? `- Test command: \`${context.commands.test}\`` : '- No test command configured'}
- Run all: \`npm test\`
- Run specific: \`npm test -- --grep pattern\`
- Watch mode: \`npm test -- --watch\`

## Coverage Requirements
- Minimum: 80% statements
- Functions: 80% coverage
- Branches: 75% coverage
- Lines: 80% coverage
`
    }
  ];
}

function testsGithubCopilot(context: RepoContext): RenderedFile[] {
  return [
    {
      path: '.github/test-conventions.md',
      content: `# Test Conventions

## Test Structure
- Test files: \`*.test.ts\` or \`*.spec.ts\`
- Location: adjacent to source or in \`__tests__/\` directory

## Test Patterns
- **Unit Tests:** Test individual functions and classes
- **Integration Tests:** Test module interactions
- **E2E Tests:** Test complete workflows

## Running Tests
${context.commands.test ? `- \`${context.commands.test}\`` : '- Configure test command in package.json'}

## Coverage: Aim for 80%
`
    }
  ];
}

function testsClaude(context: RepoContext): RenderedFile[] {
  return [
    {
      path: 'TEST-CONVENTIONS.md',
      content: `# Test Conventions

## Test Structure
- Test files: \`*.test.ts\` or \`*.spec.ts\`
- Location: adjacent to source or in \`__tests__/\` directory

## Test Patterns
- **Unit Tests:** Test individual functions and classes
- **Integration Tests:** Test module interactions
- **E2E Tests:** Test complete workflows

## Running Tests
${context.commands.test ? `- \`${context.commands.test}\`` : '- Configure test command'}

## Coverage: Aim for 80%
`
    }
  ];
}

function testsGemini(context: RepoContext): RenderedFile[] {
  return [
    {
      path: 'gemini-tests.json',
      content: JSON.stringify({
        structure: { files: '*.test.ts or *.spec.ts', location: 'adjacent to source' },
        patterns: ['Unit Tests', 'Integration Tests', 'E2E Tests'],
        coverage: '80% minimum',
        command: context.commands.test || 'npm test'
      }, null, 2) + '\n'
    }
  ];
}

function testsGeneric(context: RepoContext): RenderedFile[] {
  return [
    {
      path: '.ai-context/test-conventions.md',
      content: `${header(context)}# Test Conventions

## Test Structure
- Test files: \`*.test.ts\` or \`*.spec.ts\`
- Location: adjacent to source or in \`__tests__/\` directory

## Test Patterns
- **Unit Tests:** Test individual functions and classes
- **Integration Tests:** Test module interactions
- **E2E Tests:** Test complete workflows

## Coverage: Aim for 80%
`
    }
  ];
}

export function stageTests(context: RepoContext, target: Exclude<Target, 'all'>): RenderedFile[] {
  switch (target) {
    case 'cursor':
      return testsCursor(context);
    case 'github-copilot':
      return testsGithubCopilot(context);
    case 'claude':
      return testsClaude(context);
    case 'gemini':
      return testsGemini(context);
    case 'generic':
      return testsGeneric(context);
  }
}

// ============================================================================
// DRIFT CHECK STAGE - Common to all targets
// ============================================================================
export function stageDriftCheck(context: RepoContext): RenderedFile[] {
  return [
    {
      path: '.ai-context/drift-check.json',
      content: JSON.stringify(
        {
          lastRun: new Date().toISOString(),
          contextHash: marker(context),
          repository: context.repository.name,
          status: 'OK',
          violations: [],
          warnings: []
        },
        null,
        2
      ) + '\n'
    }
  ];
}

// ============================================================================
// CLAUDEMD STAGE - Target-specific implementations
// ============================================================================
function claudemdClaude(context: RepoContext): RenderedFile[] {
  return [
    {
      path: '.claude/instructions.md',
      content: `${header(context)}# AI Assistant Guidelines for ${context.repository.name}

## Reasoning Rules
1. **Use observable evidence only** — Base decisions on actual code, not assumptions
2. **Preserve architecture** — Respect module boundaries and existing patterns
3. **Ask before changing generated context** — Generated files are read-only unless explicit permission given
4. **Follow constraints** — Never violate stated project constraints
5. **Document decisions** — Explain architectural changes in ADRs

## Tone & Interaction
- Be precise and concise
- Avoid vague recommendations
- Provide code examples with context
- Explain trade-offs when relevant
- Reference actual files and line numbers

## Code Generation
- Match existing code style and patterns
- Use established naming conventions
- Respect module boundaries
- Add appropriate error handling
- Include tests for new functionality

## When Uncertain
- Ask clarifying questions
- Provide multiple options with trade-offs
- Reference relevant ADRs and documentation
- Suggest running tests or drift checks
`
    }
  ];
}

function claudemdCursor(context: RepoContext): RenderedFile[] {
  return [
    {
      path: '.cursor/rules/900-claude-instructions.mdc',
      content: `---
alwaysApply: true
name: "900-claude-instructions"
description: "Custom AI behavioral guidelines"
---
${header(context)}# AI Assistant Guidelines for ${context.repository.name}

## Reasoning Rules
1. **Use observable evidence only** — Base decisions on actual code, not assumptions
2. **Preserve architecture** — Respect module boundaries and existing patterns
3. **Ask before changing generated context** — Generated files are read-only unless explicit permission given

## Code Generation
- Match existing code style and patterns
- Use established naming conventions
- Respect module boundaries
`
    }
  ];
}

function claudemdGeneric(context: RepoContext): RenderedFile[] {
  return [
    {
      path: '.ai-context/ai-instructions.md',
      content: `${header(context)}# AI Assistant Guidelines for ${context.repository.name}

## Reasoning Rules
1. **Use observable evidence only** — Base decisions on actual code, not assumptions
2. **Preserve architecture** — Respect module boundaries and existing patterns
3. **Ask before changing generated context** — Generated files are read-only unless explicit permission given

## Code Generation
- Match existing code style and patterns
- Use established naming conventions
- Respect module boundaries
`
    }
  ];
}

export function stageClaudemd(context: RepoContext, target: Exclude<Target, 'all'>): RenderedFile[] {
  switch (target) {
    case 'claude':
      return claudemdClaude(context);
    case 'cursor':
      return claudemdCursor(context);
    case 'github-copilot':
      return []; // GitHub Copilot doesn't need claudemd
    case 'gemini':
      return []; // Gemini doesn't need claudemd
    case 'generic':
      return claudemdGeneric(context);
  }
}

// ============================================================================
// PIPELINE ORCHESTRATION
// ============================================================================
export function stagePipeline(context: RepoContext, target: Exclude<Target, 'all'>, stages?: PromptStage[]): StageOutput[] {
  const stageMap: Record<Exclude<PromptStage, 'all'>, (ctx: RepoContext, tgt: Exclude<Target, 'all'>) => RenderedFile[]> = {
    'scanner': (ctx) => stageScanner(ctx),
    'context-generator': (ctx, tgt) => stageContextGenerator(ctx, tgt),
    'architecture': (ctx, tgt) => stageArchitecture(ctx, tgt),
    'standards': (ctx, tgt) => stageStandards(ctx, tgt),
    'tests': (ctx, tgt) => stageTests(ctx, tgt),
    'drift-check': (ctx) => stageDriftCheck(ctx),
    'claudemd': (ctx, tgt) => stageClaudemd(ctx, tgt)
  };

  const execution: Exclude<PromptStage, 'all'>[] = stages === undefined || stages.includes('all')
    ? ['scanner', 'context-generator', 'architecture', 'standards', 'tests', 'drift-check', 'claudemd']
    : stages.filter((s) => s !== 'all') as Exclude<PromptStage, 'all'>[];

  const results: StageOutput[] = [];
  for (const stage of execution) {
    const generator = stageMap[stage];
    if (!generator) {
      results.push({
        stage,
        target,
        files: [],
        timestamp: new Date().toISOString(),
        status: 'skipped'
      });
      continue;
    }
    const files = generator(context, target);
    results.push({
      stage,
      target,
      files,
      timestamp: new Date().toISOString(),
      status: 'success'
    });
  }
  return results;
}
